/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package geral;

import dao.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Diogo Figueiredo
 */
public class GEHome extends javax.swing.JFrame {

    /**
     * Creates new form GEHome
     */
    Conexao conectar = new Conexao();
    DefaultListModel modelo;

    public GEHome() throws ClassNotFoundException, SQLException {
        initComponents();
        conectar.abrirCon();
        listaNomes.setVisible(false);
        listaNomes1.setVisible(false);
        modelo = new DefaultListModel();
        listaNomes.setModel(modelo);
        listaNomes1.setModel(modelo);
        DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo1));
        readeJtable();
        btnGravarNovoCadastro.setVisible(false);
    }

    //So mais um comentario teste
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMaster = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtPai = new javax.swing.JTextField();
        txtMae = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCpfMae = new javax.swing.JTextField();
        txtEscola = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCpfPai = new javax.swing.JTextField();
        enviarEmail = new javax.swing.JToggleButton();
        enviarWatsapp = new javax.swing.JToggleButton();
        txtNomes = new javax.swing.JTextField();
        listaNomes = new javax.swing.JList<>();
        lblImagemFundo = new javax.swing.JLabel();
        PainelCadatro = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNome2 = new javax.swing.JTextField();
        txtIdCad = new javax.swing.JTextField();
        txtPai2 = new javax.swing.JTextField();
        txtMae2 = new javax.swing.JTextField();
        txtIdade2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        txtCpfMae2 = new javax.swing.JTextField();
        txtEscola2 = new javax.swing.JTextField();
        txtEndereco2 = new javax.swing.JTextField();
        txtTelefone2 = new javax.swing.JTextField();
        txtCpfPai2 = new javax.swing.JTextField();
        btnNovoCadastro = new javax.swing.JToggleButton();
        btnGravarNovoCadastro = new javax.swing.JToggleButton();
        btnExcluirCadastro = new javax.swing.JToggleButton();
        btnGravarCadastro = new javax.swing.JToggleButton();
        listaNomes1 = new javax.swing.JList<>();
        txtNomes1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelMasterMouseClicked(evt);
            }
        });

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1319, 799));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1333, 811));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Idade", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 1220, 360));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Idade");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setText("Pai");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setText("Mae");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setText("Nome");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 300, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));
        jPanel1.add(txtPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 300, -1));
        jPanel1.add(txtMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 300, -1));
        jPanel1.add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 80, -1));

        jLabel6.setText("CPF");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel7.setText("CPF");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel8.setText("TelefoneContato");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, 30));

        jLabel9.setText("Endereço");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabel10.setText("Escola");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jLabel11.setText("EmailContato");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 250, -1));
        jPanel1.add(txtCpfMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 160, -1));
        jPanel1.add(txtEscola, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 250, -1));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 250, -1));
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 240, 30));
        jPanel1.add(txtCpfPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 160, -1));

        enviarEmail.setText("Enviar E-mail");
        jPanel1.add(enviarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 160, 50));

        enviarWatsapp.setText("Enviar Watsapp");
        jPanel1.add(enviarWatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, 160, 50));

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 1220, 220));

        txtNomes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNomes.setOpaque(true);
        txtNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomesMouseClicked(evt);
            }
        });
        txtNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomesActionPerformed(evt);
            }
        });
        txtNomes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomesKeyReleased(evt);
            }
        });
        jLayeredPane1.add(txtNomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 540, 40));

        listaNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaNomesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaNomesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listaNomesMouseReleased(evt);
            }
        });
        jLayeredPane1.add(listaNomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 540, 80));

        lblImagemFundo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novatelage.jpg"))); // NOI18N
        lblImagemFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagemFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblImagemFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImagemFundo.setName(""); // NOI18N
        jLayeredPane1.add(lblImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1330, 810));

        PainelMaster.addTab("INFORMACOES", jLayeredPane1);

        PainelCadatro.setPreferredSize(new java.awt.Dimension(800, 200));
        PainelCadatro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Id");
        jLabel23.setAlignmentX(2.0F);
        PainelCadatro.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Idade");
        jLabel24.setAlignmentX(2.0F);
        PainelCadatro.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Pai");
        jLabel25.setAlignmentX(2.0F);
        PainelCadatro.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Mae");
        jLabel26.setAlignmentX(2.0F);
        PainelCadatro.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Nome");
        jLabel27.setAlignmentX(2.0F);
        PainelCadatro.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        txtNome2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNome2.setAlignmentX(2.0F);
        txtNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome2ActionPerformed(evt);
            }
        });
        PainelCadatro.add(txtNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 270, -1));

        txtIdCad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIdCad.setAlignmentX(2.0F);
        txtIdCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCadActionPerformed(evt);
            }
        });
        PainelCadatro.add(txtIdCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 50, -1));

        txtPai2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPai2.setAlignmentX(2.0F);
        PainelCadatro.add(txtPai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 270, -1));

        txtMae2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMae2.setAlignmentX(2.0F);
        PainelCadatro.add(txtMae2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 270, -1));

        txtIdade2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIdade2.setAlignmentX(2.0F);
        PainelCadatro.add(txtIdade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 80, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("CPF");
        PainelCadatro.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("CPF");
        PainelCadatro.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Telefone Contato");
        jLabel30.setAlignmentX(2.0F);
        PainelCadatro.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 150, 40));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Endereço");
        jLabel31.setAlignmentX(2.0F);
        PainelCadatro.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Escola");
        jLabel32.setAlignmentX(2.0F);
        PainelCadatro.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Email Contato");
        jLabel33.setAlignmentX(2.0F);
        PainelCadatro.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 140, 20));

        txtEmail2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail2.setAlignmentX(2.0F);
        txtEmail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail2ActionPerformed(evt);
            }
        });
        PainelCadatro.add(txtEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 310, 30));
        PainelCadatro.add(txtCpfMae2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, 160, -1));

        txtEscola2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEscola2.setAlignmentX(2.0F);
        PainelCadatro.add(txtEscola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 340, -1));

        txtEndereco2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEndereco2.setAlignmentX(2.0F);
        PainelCadatro.add(txtEndereco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 340, -1));

        txtTelefone2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefone2.setAlignmentX(2.0F);
        PainelCadatro.add(txtTelefone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 310, 30));
        PainelCadatro.add(txtCpfPai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, 160, -1));

        btnNovoCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNovoCadastro.setText("Novo Cadastro");
        btnNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCadastroActionPerformed(evt);
            }
        });
        PainelCadatro.add(btnNovoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 50));

        btnGravarNovoCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGravarNovoCadastro.setText("Gravar Novo Cadastro");
        btnGravarNovoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarNovoCadastroMouseClicked(evt);
            }
        });
        btnGravarNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarNovoCadastroActionPerformed(evt);
            }
        });
        PainelCadatro.add(btnGravarNovoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 230, 80));

        btnExcluirCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExcluirCadastro.setText("Excluir Cadastro");
        btnExcluirCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCadastroActionPerformed(evt);
            }
        });
        PainelCadatro.add(btnExcluirCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 50));

        btnGravarCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGravarCadastro.setText("Gravar Alterações");
        btnGravarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarCadastroActionPerformed(evt);
            }
        });
        PainelCadatro.add(btnGravarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, 50));

        listaNomes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaNomes1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaNomes1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listaNomes1MouseReleased(evt);
            }
        });
        PainelCadatro.add(listaNomes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 540, 80));

        txtNomes1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomes1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNomes1.setOpaque(true);
        txtNomes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomes1MouseClicked(evt);
            }
        });
        txtNomes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomes1ActionPerformed(evt);
            }
        });
        txtNomes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomes1KeyReleased(evt);
            }
        });
        PainelCadatro.add(txtNomes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 540, 40));

        PainelMaster.addTab("CADASTROS", PainelCadatro);

        getContentPane().add(PainelMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomesKeyReleased
        ListaPesquisa();
    }//GEN-LAST:event_txtNomesKeyReleased

    private void txtNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomesActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void listaNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomesMouseClicked
        try {
            MostraPesq();
        } catch (SQLException ex) {
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomes.setText(listaNomes.getSelectedValue());
        listaNomes.setVisible(false);
    }//GEN-LAST:event_listaNomesMouseClicked

    private void listaNomesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomesMousePressed
        // TODO add your handling code here:
        try {
            MostraPesq();
        } catch (SQLException ex) {
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomes.setText(listaNomes.getSelectedValue());
        listaNomes.setVisible(false);
    }//GEN-LAST:event_listaNomesMousePressed

    private void listaNomesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomesMouseReleased
        // TODO add your handling code here:
        try {
            MostraPesq();
        } catch (SQLException ex) {
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomes.setText(listaNomes.getSelectedValue());
        listaNomes.setVisible(false);
    }//GEN-LAST:event_listaNomesMouseReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomesMouseClicked

    private void txtNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome2ActionPerformed

    private void txtIdCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCadActionPerformed

    private void txtEmail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail2ActionPerformed

    private void listaNomes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomes1MouseClicked
        try {
            MostraPesqCadastro();
        } catch (SQLException ex) {
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomes1.setText(listaNomes1.getSelectedValue());
        listaNomes1.setVisible(false);


    }//GEN-LAST:event_listaNomes1MouseClicked

    private void listaNomes1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomes1MousePressed
        try {
            MostraPesqCadastro();
        } catch (SQLException ex) {
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomes1.setText(listaNomes1.getSelectedValue());
        listaNomes1.setVisible(false);
    }//GEN-LAST:event_listaNomes1MousePressed

    private void listaNomes1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomes1MouseReleased
        try {
            MostraPesqCadastro();
        } catch (SQLException ex) {
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomes1.setText(listaNomes1.getSelectedValue());
        listaNomes1.setVisible(false);
    }//GEN-LAST:event_listaNomes1MouseReleased

    private void txtNomes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomes1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomes1MouseClicked

    private void txtNomes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomes1ActionPerformed

    private void txtNomes1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomes1KeyReleased
        ListaPesquisaCadastro();
    }//GEN-LAST:event_txtNomes1KeyReleased

    private void btnNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCadastroActionPerformed
        txtNomes1.setText("");
        txtIdCad.setText("");
        txtNome2.setText("");
        txtIdade2.setText("");
        txtPai2.setText("");
        txtCpfPai2.setText("");
        txtMae2.setText("");
        txtCpfMae2.setText("");
        txtEndereco2.setText("");
        txtTelefone2.setText("");
        txtEmail2.setText("");
        txtEscola2.setText("");
        btnGravarNovoCadastro.setVisible(true);
    }//GEN-LAST:event_btnNovoCadastroActionPerformed

    private void btnGravarNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarNovoCadastroActionPerformed


    }//GEN-LAST:event_btnGravarNovoCadastroActionPerformed

    private void btnGravarNovoCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarNovoCadastroMouseClicked
        try {
            conectar.newCad(txtNome2.getText(), Integer.parseInt(txtIdade2.getText()), txtPai2.getText(), Integer.parseInt(txtCpfPai2.getText()), txtMae2.getText(), Integer.parseInt(txtCpfMae2.getText()), txtEndereco2.getText(), Integer.parseInt(txtTelefone2.getText()), txtEmail2.getText(), txtEscola2.getText());
        } catch (SQLException ex) {
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGravarNovoCadastroMouseClicked

    private void PainelMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelMasterMouseClicked

    }//GEN-LAST:event_PainelMasterMouseClicked

    private void btnGravarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGravarCadastroActionPerformed

    private void btnExcluirCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCadastroActionPerformed

        /* conectar.executaSql("delete from `bancoge`.`pessoasge` WHERE (`id` = '" + Integer.parseInt(txtIdCad.getText()) + "')");
       
        
        melhorar este metodo de exclusao de cadastro.
        
        
        */

    }//GEN-LAST:event_btnExcluirCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GEHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GEHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GEHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GEHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GEHome().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCadatro;
    private javax.swing.JTabbedPane PainelMaster;
    private javax.swing.JToggleButton btnExcluirCadastro;
    private javax.swing.JToggleButton btnGravarCadastro;
    private javax.swing.JToggleButton btnGravarNovoCadastro;
    private javax.swing.JToggleButton btnNovoCadastro;
    private javax.swing.JToggleButton enviarEmail;
    private javax.swing.JToggleButton enviarWatsapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblImagemFundo;
    private javax.swing.JList<String> listaNomes;
    private javax.swing.JList<String> listaNomes1;
    private javax.swing.JTextField txtCpfMae;
    private javax.swing.JTextField txtCpfMae2;
    private javax.swing.JTextField txtCpfPai;
    private javax.swing.JTextField txtCpfPai2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEndereco2;
    private javax.swing.JTextField txtEscola;
    private javax.swing.JTextField txtEscola2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdCad;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtIdade2;
    private javax.swing.JTextField txtMae;
    private javax.swing.JTextField txtMae2;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome2;
    private javax.swing.JTextField txtNomes;
    private javax.swing.JTextField txtNomes1;
    private javax.swing.JTextField txtPai;
    private javax.swing.JTextField txtPai2;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTelefone2;
    // End of variables declaration//GEN-END:variables

// Metodo que busca no banco de dados os nomes a partir da pesquisa e preenche o jlist da tela informacoes.
    public void ListaPesquisa() {
        try {
            conectar.executaSql("select * from pessoasge where nome like"
                    + " '" + txtNomes.getText() + "%' order by nome");
            modelo.removeAllElements();
            int v = 0;
            while (conectar.rs.next() & v < 5) {
                modelo.addElement(conectar.rs.getString("nome"));
                v++;
            }
            if (v >= 1) {
                listaNomes.setVisible(true);
            } else {
                listaNomes.setVisible(false);
            }
        } catch (Exception e) {
        }
    }

    // Metodo que busca no banco de dados os nomes a partir da pesquisa e preenche o jlist da tela de cadastro.
    public void ListaPesquisaCadastro() {
        try {
            conectar.executaSql("select * from pessoasge where nome like"
                    + " '" + txtNomes1.getText() + "%' order by nome");
            modelo.removeAllElements();
            int v = 0;
            while (conectar.rs.next() & v < 5) {
                modelo.addElement(conectar.rs.getString("nome"));
                v++;
            }
            if (v >= 1) {
                listaNomes1.setVisible(true);
            } else {
                listaNomes1.setVisible(false);
            }
        } catch (Exception e) {
        }
    }

    // Metodo para preencher os campos do formulário a partir do nome selecionado no jlist
    public void MostraPesq() throws SQLException {
        String linha = listaNomes.getSelectedValue();
        List<PessoaAluno> pessoas = new ArrayList<>();
        conectar.executaSql("SELECT * FROM pessoasge where 1");
        while (conectar.rs.next()) {
            String nome = conectar.rs.getString("nome");
            if (nome.equals(linha)) {

                txtId.setText(conectar.rs.getString("id"));
                txtNome.setText(conectar.rs.getString("nome"));
                txtIdade.setText(conectar.rs.getString("idade"));
                txtPai.setText(conectar.rs.getString("pai"));
                txtCpfPai.setText(conectar.rs.getString("cpfPai"));
                txtMae.setText(conectar.rs.getString("mae"));
                txtCpfMae.setText(conectar.rs.getString("cpfMae"));
                txtEndereco.setText(conectar.rs.getString("endereco"));
                txtTelefone.setText(conectar.rs.getString("telefonecontato"));
                txtEmail.setText(conectar.rs.getString("emailcontato"));
                txtEscola.setText(conectar.rs.getString("escola"));

            }
        }
    }
    // Metodo para preencher os campos do formulário de Cadastro a partir do nome selecionado no jlist

    public void MostraPesqCadastro() throws SQLException {
        String linha = listaNomes1.getSelectedValue();
        List<PessoaAluno> pessoas = new ArrayList<>();
        conectar.executaSql("SELECT * FROM pessoasge where 1");
        while (conectar.rs.next()) {
            String nome = conectar.rs.getString("nome");
            if (nome.equals(linha)) {

                txtIdCad.setText(conectar.rs.getString("id"));
                txtNome2.setText(conectar.rs.getString("nome"));
                txtIdade2.setText(conectar.rs.getString("idade"));
                txtPai2.setText(conectar.rs.getString("pai"));
                txtCpfPai2.setText(conectar.rs.getString("cpfPai"));
                txtMae2.setText(conectar.rs.getString("mae"));
                txtCpfMae2.setText(conectar.rs.getString("cpfMae"));
                txtEndereco2.setText(conectar.rs.getString("endereco"));
                txtTelefone2.setText(conectar.rs.getString("telefonecontato"));
                txtEmail2.setText(conectar.rs.getString("emailcontato"));
                txtEscola2.setText(conectar.rs.getString("escola"));

            }
        }
    }

    public List<PessoaAluno> reade() {

        List<PessoaAluno> pessoas = new ArrayList<>();
        try {
            conectar.executaSql("select * from pessoasge");

            while (conectar.rs.next()) {
                PessoaAluno ppessoa = new PessoaAluno() {
                };
                ppessoa.setId(conectar.rs.getInt("id"));
                ppessoa.setNome(conectar.rs.getString("nome"));
                ppessoa.setIdade(conectar.rs.getInt("idade"));
                ppessoa.setJaneiro(conectar.rs.getString("janeiro"));
                ppessoa.setFevereiro(conectar.rs.getString("fevereiro"));
                ppessoa.setMarco(conectar.rs.getString("marco"));
                ppessoa.setAbril(conectar.rs.getString("abril"));
                ppessoa.setMaio(conectar.rs.getString("maio"));
                ppessoa.setJunho(conectar.rs.getString("junho"));
                ppessoa.setJulho(conectar.rs.getString("julho"));
                ppessoa.setAgosto(conectar.rs.getString("agosto"));
                ppessoa.setSetembro(conectar.rs.getString("setembro"));
                ppessoa.setOutubro(conectar.rs.getString("outubro"));
                ppessoa.setNovembro(conectar.rs.getString("novembro"));
                ppessoa.setDezembro(conectar.rs.getString("dezembro"));

                pessoas.add(ppessoa);
            }
        } catch (Exception e) {
        }
        return pessoas;
    }

    public void readeJtable() {
        DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
        for (PessoaAluno p : reade()) {
            modelo1.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getIdade(),
                p.Janeiro(),
                p.Fevereiro(),
                p.Marco(),
                p.Abril(),
                p.Maio(),
                p.Junho(),
                p.Julho(),
                p.Agosto(),
                p.Setembro(),
                p.Outubro(),
                p.Novembro(),
                p.Dezembro(),});
        }
    }

}
