/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package geral;

import dao.Conexao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diogo
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TesteExibicao
     */
    DefaultListModel modelo;
    Conexao conectar = new Conexao();

    //construtor da classe
    public TelaCadastro() throws SQLException, ClassNotFoundException {

        initComponents();
        conectar.abrirCon();
        painelCadastro.setVisible(false);
        btnExcluirCadastro.setVisible(false);
        listaNomes.setVisible(false); //inicia lista nomes tela cadastro
        modelo = new DefaultListModel();
        listaNomes.setModel(modelo);
        lblStatusCad.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHomeTelaCadastro = new javax.swing.JToggleButton();
        painelCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtPai = new javax.swing.JTextField();
        txtMae = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCpfMae = new javax.swing.JTextField();
        txtEscola = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCpfPai = new javax.swing.JTextField();
        enviarEmail = new javax.swing.JToggleButton();
        enviarWatsapp = new javax.swing.JToggleButton();
        btnGravarNovoCadastro = new javax.swing.JButton();
        lblStatusCad = new javax.swing.JLabel();
        btnExcluirCadastro = new javax.swing.JButton();
        txtNomes = new javax.swing.JTextField();
        listaNomes = new javax.swing.JList<>();
        labelTituloPesquisa = new javax.swing.JLabel();
        btnNovoCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHomeTelaCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconHome.png"))); // NOI18N
        btnHomeTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeTelaCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnHomeTelaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        painelCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Id");
        painelCadastro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Idade");
        painelCadastro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Pai");
        painelCadastro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Mae");
        painelCadastro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Nome");
        painelCadastro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        painelCadastro.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 300, -1));

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        painelCadastro.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, -1));
        painelCadastro.add(txtPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 300, -1));
        painelCadastro.add(txtMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 300, -1));
        painelCadastro.add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("CPF");
        painelCadastro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("CPF");
        painelCadastro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Telefone");
        painelCadastro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Endereço");
        painelCadastro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Escola");
        painelCadastro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("EmailContato");
        painelCadastro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        painelCadastro.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 250, -1));
        painelCadastro.add(txtCpfMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 160, -1));
        painelCadastro.add(txtEscola, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, -1));
        painelCadastro.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));
        painelCadastro.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 300, 30));
        painelCadastro.add(txtCpfPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 160, -1));

        enviarEmail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        enviarEmail.setText("Enviar E-mail");
        painelCadastro.add(enviarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 200, 50));

        enviarWatsapp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        enviarWatsapp.setText("Enviar Watsapp");
        painelCadastro.add(enviarWatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 200, 50));

        btnGravarNovoCadastro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGravarNovoCadastro.setText("GRAVAR");
        btnGravarNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarNovoCadastroActionPerformed(evt);
            }
        });
        painelCadastro.add(btnGravarNovoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 130, 60));
        painelCadastro.add(lblStatusCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 440, 50));

        getContentPane().add(painelCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 1210, 330));

        btnExcluirCadastro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnExcluirCadastro.setForeground(new java.awt.Color(255, 0, 0));
        btnExcluirCadastro.setText("EXCLUIR");
        btnExcluirCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluirCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 140, 50));

        txtNomes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNomes.setOpaque(true);
        txtNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomesMouseClicked(evt);
            }
        });
        txtNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomesActionPerformed(evt);
            }
        });
        txtNomes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomesKeyReleased(evt);
            }
        });
        getContentPane().add(txtNomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 680, 60));

        listaNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaNomesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaNomesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listaNomesMouseReleased(evt);
            }
        });
        getContentPane().add(listaNomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 680, 100));

        labelTituloPesquisa.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        labelTituloPesquisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloPesquisa.setText("PESQUISA");
        getContentPane().add(labelTituloPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 680, 60));

        btnNovoCadastro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnNovoCadastro.setText("NOVO");
        btnNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void btnHomeTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeTelaCadastroActionPerformed
        this.dispose();
        PrincipalGE tela;
        try {
            tela = new PrincipalGE();
            tela.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHomeTelaCadastroActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnExcluirCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCadastroActionPerformed
        try {
            conectar.delCad(Integer.parseInt(txtId.getText()));
            //txtMsgStatusCadastro.setVisible(true);
            //txtMsgStatusCadastro.setText("Cadastro Excluido com Sucesso");

        } catch (SQLException ex) {
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparCampos();

    }//GEN-LAST:event_btnExcluirCadastroActionPerformed

    private void txtNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomesMouseClicked

    private void txtNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomesActionPerformed

    private void txtNomesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomesKeyReleased
    }//GEN-LAST:event_txtNomesKeyReleased

    private void listaNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomesMouseClicked
        btnExcluirCadastro.setVisible(true);
        try {
            MostraPesqCadastro();
        } catch (SQLException ex) {
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomes.setText(listaNomes.getSelectedValue());
        listaNomes.setVisible(false);

    }//GEN-LAST:event_listaNomesMouseClicked

    private void listaNomesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaNomesMousePressed

    private void listaNomesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomesMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_listaNomesMouseReleased

    private void btnNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCadastroActionPerformed
        painelCadastro.setVisible(true);
        limparCampos();


    }//GEN-LAST:event_btnNovoCadastroActionPerformed

    private void txtNomesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomesKeyPressed
        painelCadastro.setVisible(true);
        ListaPesquisaCadastro();


    }//GEN-LAST:event_txtNomesKeyPressed

    private void btnGravarNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarNovoCadastroActionPerformed
        try {
            conectar.newCad(txtNome.getText(), Integer.parseInt(txtIdade.getText()), txtPai.getText(), Integer.parseInt(txtCpfPai.getText()), txtMae.getText(), Integer.parseInt(txtCpfMae.getText()), txtEndereco.getText(), Integer.parseInt(txtTelefone.getText()), txtEmail.getText(), txtEscola.getText());
            lblStatusCad.setVisible(true);
            lblStatusCad.setText("CADASTRO REALIZADO COM SUCESSO");

        } catch (SQLException ex) {
            
            Logger.getLogger(GEHome.class.getName()).log(Level.SEVERE, null, ex);
            lblStatusCad.setVisible(true);
            lblStatusCad.setText("ERRO NO CADASTRO");

        }
        limparCampos();
    }//GEN-LAST:event_btnGravarNovoCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCadastro().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirCadastro;
    private javax.swing.JButton btnGravarNovoCadastro;
    private javax.swing.JToggleButton btnHomeTelaCadastro;
    private javax.swing.JButton btnNovoCadastro;
    private javax.swing.JToggleButton enviarEmail;
    private javax.swing.JToggleButton enviarWatsapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelTituloPesquisa;
    private javax.swing.JLabel lblStatusCad;
    private javax.swing.JList<String> listaNomes;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JTextField txtCpfMae;
    private javax.swing.JTextField txtCpfPai;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEscola;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtMae;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomes;
    private javax.swing.JTextField txtPai;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    // Metodo que busca no banco de dados os nomes a partir da pesquisa e preenche o jlist da tela de cadastro.
    public void ListaPesquisaCadastro() {
        try {
            conectar.executaSql("select * from pessoasge where nome like"
                    + " '" + txtNomes.getText() + "%' order by nome");
            modelo.removeAllElements();
            int v = 0;
            while (conectar.rs.next() & v < 5) {
                modelo.addElement(conectar.rs.getString("nome"));
                v++;
            }
            if (v >= 1) {
                listaNomes.setVisible(true);
            } else {
                listaNomes.setVisible(false);
            }
        } catch (Exception e) {
        }
    }

    //metodo que limpa todos os campos do painel de cadastro
    public void limparCampos() {
        txtNomes.setText("");
        txtId.setText("");
        txtNome.setText("");
        txtIdade.setText("");
        txtPai.setText("");
        txtCpfPai.setText("");
        txtMae.setText("");
        txtCpfMae.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtEscola.setText("");
    }

    // Metodo para preencher os campos do formulário de Cadastro a partir do nome selecionado no jlist
    public void MostraPesqCadastro() throws SQLException {
        String linha = listaNomes.getSelectedValue();
        conectar.executaSql("SELECT * FROM pessoasge where 1");
        while (conectar.rs.next()) {
            String nome = conectar.rs.getString("nome");
            if (nome.equals(linha)) {

                txtId.setText(conectar.rs.getString("id"));
                txtNome.setText(conectar.rs.getString("nome"));
                txtIdade.setText(conectar.rs.getString("idade"));
                txtPai.setText(conectar.rs.getString("pai"));
                txtCpfPai.setText(conectar.rs.getString("cpfPai"));
                txtMae.setText(conectar.rs.getString("mae"));
                txtCpfMae.setText(conectar.rs.getString("cpfMae"));
                txtEndereco.setText(conectar.rs.getString("endereco"));
                txtTelefone.setText(conectar.rs.getString("telefonecontato"));
                txtEmail.setText(conectar.rs.getString("emailcontato"));
                txtEscola.setText(conectar.rs.getString("escola"));

            }
        }
    }
}
